# Generated by Django 4.0.6 on 2023-08-02 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_peptidemodsview_proteinmatchesview'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeptideSpectrumMatchesMatView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psm_code', models.BigIntegerField(blank=True, null=True)),
                ('artificial_peptide_code', models.TextField(blank=True, null=True)),
                ('peptide_sequence', models.CharField(blank=True, max_length=50, null=True)),
                ('retention_time', models.FloatField(blank=True, null=True)),
                ('mass_to_charge', models.FloatField(blank=True, null=True)),
                ('q_value', models.FloatField(blank=True, null=True)),
                ('charge', models.SmallIntegerField(blank=True, null=True)),
                ('search_identifier', models.TextField(blank=True, null=True)),
                ('spectrum_reference', models.TextField(blank=True, null=True)),
                ('ion_frac', models.FloatField(blank=True, null=True)),
                ('delt_cn', models.FloatField(blank=True, null=True)),
                ('delt_lcn', models.FloatField(blank=True, null=True)),
                ('percolator_score', models.FloatField(blank=True, null=True)),
                ('pep', models.FloatField(blank=True, null=True)),
                ('x_corr', models.FloatField(blank=True, null=True)),
                ('sp_score', models.FloatField(blank=True, null=True)),
                ('sp_rank', models.FloatField(blank=True, null=True)),
                ('expectation_value', models.FloatField(blank=True, null=True)),
                ('matched_ions', models.SmallIntegerField(blank=True, null=True)),
                ('total_ions', models.SmallIntegerField(blank=True, null=True)),
                ('num_matched_peptides', models.IntegerField(blank=True, null=True)),
                ('peptide_mass', models.FloatField(blank=True, null=True)),
                ('is_best_spectrum', models.BooleanField(blank=True, null=True)),
                ('peptide_modifications', models.TextField(blank=True, null=True)),
                ('uniprot_ids', models.TextField(blank=True, null=True)),
                ('protein_names', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'peptide_spectrum_matches_mat_view',
                'managed': False,
            },
        ),
    ]
