# Generated by Django 4.2.3 on 2024-01-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0004_peptidespectrummatchesmatview'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peptide_length_min', models.IntegerField(blank=True, null=True)),
                ('peptide_length_max', models.IntegerField(blank=True, null=True)),
                ('biological_material_name', models.TextField(blank=True, null=True)),
                ('disease_name', models.TextField(blank=True, null=True)),
                ('mhc_class', models.TextField(blank=True, null=True)),
                ('dignity', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'query_count',
                'managed': False,
            },
        ),
    ]
