# Generated by Django 4.2.14 on 2024-08-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0005_querycount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spectra',
            fields=[
                ('spectrum_code', models.BigAutoField(primary_key=True, serialize=False)),
                ('spectrum', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'spectra',
                'managed': False,
            },
        ),
    ]
